enum Events : int
{
    LOGIN = 1,
    ADD_FRIEND,
    REMOVE_FRIEND,
    GET_FRIENDS,
    GET_INVENTORY,
    GET_WORLD,
    REMOVE_ITEM,
    CREATE_ITEM,
    GET_POSITION,
    UPDATE_POSITION,
    PICKUP_ITEM,
    PLACE_ITEM,
    OPEN_CHAT,
    SEND_CHAT,
    RECEIVE_CHAT
}
